export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FILTER_PRODUCTS_BY_SIZE = "FILTER_PRODUCTS_BY_SIZE";
export const ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE";
export const ADD_TO_CART = "ADD_TO_CART";
export const SUB_TO_CART = "SUB_TO_CART";
// export const ADDED_QUANTITY = "ADDED_QUANTITY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
